name:                lang
version:             0.1.0.0
github:              "jockee/lang"
license:             BSD3
author:              "jockee"
maintainer:          "example@example.com"
copyright:           "2021 jockee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lang#readme>

dependencies:
- base >= 4.14 && < 5
- extra
- parser-combinators
- parsec
- indents
- string-interpolate
- megaparsec
- protolude
- text
- haskeline
- transformers
- mtl
- pretty-simple
- hspec
- containers
- hspec-discover
- aeson
- vector
- scientific
- unordered-containers
- bytestring
- haskeline
- exceptions
- split
- http-client-tls
- http-types
- case-insensitive
- http-client
- safe

library:
  default-extensions: &lang-default-extensions
    LambdaCase
    GeneralizedNewtypeDeriving
    StrictData
    ScopedTypeVariables
    DerivingStrategies
    ImportQualifiedPost
    OverloadedStrings
    TemplateHaskell
    QuasiQuotes
    TypeFamilies
    MultiParamTypeClasses
  source-dirs: src
  ghc-options: -Weverything -Wno-all-missed-specialisations -Wno-missed-specialisations -Wno-missing-exported-signatures -Wno-missing-import-lists -Wno-missing-local-signatures -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe -Wno-missing-safe-haskell-mode -Wno-type-defaults -Wno-name-shadowing -O0 -Wno-incomplete-patterns -fwrite-ide-info -hiedir=.hie

executables:
  langc:
    default-extensions: *lang-default-extensions
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie
    dependencies:
    - lang

tests:
  lang-test:
    main:                Main.hs
    default-extensions: *lang-default-extensions
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lang
